/**
 * Fixed Review changes plus feed configuration (no runtime customization).
 * Mirrors prototype settings from the dashboard playground screenshots.
 */
export const reviewChangesPlusFeedProps = {
	/** Only show recent-changes items above Lift Wing REVERT_RISK_THRESHOLDS.upperLoose (dashboard + playground). */
	requireRecentChangesMeetRevertRiskThresholds: true,
	showRevertRisk: false,
	showRevertRiskFlags: true,
	revertRiskFlagsInBox: true,
	verboseFlags: false,
	showRevertedFlag: false,
	showSourceIcons: false,
	showSourceSubtitles: false,
	showDelta: false,
	deltaFormatParentheses: false,
	source: "mixed" as const,
	recentChangesRatio: 30,
	pagesAndUsersRatio: 0,
	pagesAndUsersLatestRatio: 20,
	collaboratorsRatio: 0,
	pagesIveEditedRatio: 20,
	relatedChangesRatio: 10,
	title: "Review changes plus",
	hideDescription: false,
	showUsernameAtPrefix: false,
	showUserIcon: true,
	flagsBelowUsername: true,
	simplifiedTimestamp: true,
	timestampPosition: "rightOfUsername" as const,
	showSummaryCutout: false,
	showEmptyEditSummary: true,
	showModuleBorder: true,
	showReviewButton: false,
	showDismissButton: false,
	showRecommendationFlags: true,
	showEditCheckOtherFlag: true,
	showToneCheckFlag: true,
	showDebugChecks: false,
	highlightUnviewed: true,
	unviewedBorder: false,
	viewedBorder: false,
	lastClickedHighlight: false,
	showArrowInTopRight: false,
	showShortDescription: true,
	showShortDescriptionSeparator: true,
	showOnWatchlistLabel: false,
	unifiedTitle: false,
	showStructuredDeltasForFlaggedUnviewed: true,
}
